routes/vessel.py
from flask import Blueprint,session,redirect,url_for,request,flash, render_template
from models import db, Vessel, VesselDetail,VoyageInfo
from routes.decorators import login_required, admin_required


vessel_bp = Blueprint("vessel",__name__)


@vessel_bp.route("/vessel/new", methods=["GET", "POST"])
@login_required # 로그인 여부 확인 -> 비 로그인시 로그인 페이지 이동
@admin_required  
def vessel_new():
    
    if request.method == "POST":
        name = request.form.get("name")
        imo_number = request.form.get("imo_number")
        ship_type = request.form.get("ship_type")
        ship_size = request.form.get("ship_size")
        flag = request.form.get("flag")
        ship_code = request.form.get("ship_code")
        vessel_ro = request.form.get("vessel_ro")
        vessel_class = request.form.get("vessel_class")
        built_year = request.form.get("built_year")
        team = request.form.get("team")
        crew = request.form.get("crew")
        
        if Vessel.query.filter_by(imo_number=imo_number).first():
            flash("이미 등록된 IMO 번호입니다.", "error")
        elif Vessel.query.filter_by(name=name).first():
            flash("이미 등록된 선박 이름입니다.", "error")    
        else:
            new_vessel = Vessel(
            name=name, 
            imo_number=imo_number, 
            ship_type=ship_type, 
            ship_size=ship_size, 
            flag=flag
            )
            
            new_vessel_detail = VesselDetail(
            ship_code=ship_code,
            vessel_ro=vessel_ro,
            vessel_class=vessel_class,
            built_year=built_year,
            team = team,
            crew = crew
            ) 
            
            new_vessel.detail = new_vessel_detail  # Vessel과 VesselDetail 연결
            
            db.session.add(new_vessel)
            db.session.commit()
            flash("선박 등록이 완료되었습니다.", "success")
            return redirect(url_for("vessel.vessel_list"))  # 선박 등록 후 선박 목록 페이지로 리디렉션
    
    return render_template("vessel/vessel_new.html")
    

@vessel_bp.route("/vessel/list", methods=["GET"])
@login_required # 로그인 여부 확인 -> 비 로그인시 로그인 페이지 이동
def vessel_list():
    # 1. URL 쿼리 파라미터에서 검색조건 읽기
    name = request.args.get("name","")
    ship_type = request.args.get("ship_type","")
    flag = request.args.get("flag","")

    # 2. 기본 쿼리 시작
    query = Vessel.query
    
    # 3. 조건이 있으면 필터 추가
    if name:
        query = query.filter(Vessel.name.like(f"%{name}%"))
    if ship_type:
        query = query.filter_by(ship_type=ship_type)
    if flag:
        query = query.filter_by(flag=flag)
       
    # vessels = query.all()
    # 위 코드가 아래처럼 페이지 네이션 됨
    
    page = request.args.get("page",1,type=int) # url에서 페이지 번호 읽기
    pagination = query.paginate(page=page, per_page=20 , error_out=False)
    vessels = pagination.items
     
    # 4. 최종 실행
    return render_template("vessel/vessel_list.html", vessels=vessels, name=name, ship_type=ship_type,flag=flag,pagination=pagination)  # vessel_list.html 템플릿 렌더링



@vessel_bp.route("/vessel/<int:vessel_id>", methods=["GET"])
@login_required # 로그인 여부 확인 -> 비 로그인시 로그인 페이지 이동
def vessel_detail(vessel_id):
    vessel = Vessel.query.get_or_404(vessel_id)# DB에서 해당 ID의 선박 정보 조회, 없으면 404 에러)   
    return render_template("vessel/vessel_detail.html", vessel=vessel)  # vessel_list.html 템플릿 렌더링



@vessel_bp.route("/vessel/<int:vessel_id>/edit", methods=["GET", "POST"])
@login_required # 로그인 여부 확인 -> 비 로그인시 로그인 페이지 이동
@admin_required
def vessel_edit(vessel_id):
    
    vessel = Vessel.query.get_or_404(vessel_id)# DB에서 해당 ID의 선박 정보 조회, 없으면 404 에러)   

    if request.method == "POST":
        name = request.form.get("name")
        imo_number = request.form.get("imo_number")
        ship_type = request.form.get("ship_type")
        ship_size = request.form.get("ship_size")
        flag = request.form.get("flag")
        ship_code = request.form.get("ship_code")
        vessel_ro = request.form.get("vessel_ro")
        vessel_class = request.form.get("vessel_class")
        built_year = request.form.get("built_year")
        team = request.form.get("team")
        crew = request.form.get("crew")
        
        vessel.name = name
        vessel.imo_number = imo_number
        vessel.ship_type = ship_type
        vessel.ship_size = ship_size
        vessel.flag = flag
        vessel.detail.ship_code = ship_code
        vessel.detail.vessel_ro = vessel_ro
        vessel.detail.vessel_class = vessel_class
        vessel.detail.built_year = built_year
        vessel.detail.team = team
        vessel.detail.crew = crew
        
        vessel.detail.vessel = vessel
        db.session.commit()
        flash("선박 정보가 수정되었습니다.","success")
        return redirect(url_for("vessel.vessel_detail", vessel_id=vessel.id))  # 수정 후 선박 상세 페이지로 리디렉션
    
    return render_template("vessel/vessel_edit.html", vessel=vessel)  # vessel_edit.html 템플릿 렌더링



@vessel_bp.route("/vessel/<int:vessel_id>/delete", methods=["POST"])
@login_required # 로그인 여부 확인 -> 비 로그인시 로그인 페이지 이동
@admin_required
def vessel_delete(vessel_id):
      
    vessel = Vessel.query.get_or_404(vessel_id)# DB에서 해당 ID의 선박 정보 조회, 없으면 404 에러)   
    
    try:
        db.session.delete(vessel.detail)
    except Exception:
        pass
        
    db.session.delete(vessel)
    db.session.commit()
    flash("선박 정보가 삭제되었습니다.","success")
    return redirect(url_for("vessel.vessel_list"))




@vessel_bp.route("/voyage" , methods=["GET"])
@login_required # 로그인 여부 확인 -> 비 로그인시 로그인 페이지 이동
def voyage_list():
    vessel_name = request.args.get("vessel_name", "")
    line = request.args.get("line", "")
    s_crew = request.args.get("s_crew", "")
    supervisor = request.args.get("supervisor", "")
    
    query = VoyageInfo.query
    
    if vessel_name:
        query = query.filter(VoyageInfo.vessel_name.like(f"%{vessel_name}%"))
    if line:
        query = query.filter(VoyageInfo.line.like(f"%{line}%"))
    if supervisor:
          # 담당감독 또는 운항감독 중 하나라도 일치하면 검색
        query = query.filter(
            (VoyageInfo.safety_supervisor.like(f"%{supervisor}%")) |
            (VoyageInfo.ops_supervisor.like(f"%{supervisor}%"))
          )
    if s_crew:
        query =query.filter(
            (VoyageInfo.captain.like(f"%{s_crew}%")) |
            (VoyageInfo.chief_engineer.like(f"%{s_crew}%"))
        )
               
    page = request.args.get("page",1,type=int)
    pagination = query.order_by(VoyageInfo.vessel_name).paginate(page=page, per_page=20, error_out=False)   
    voyages = pagination.items
    
    return render_template("vessel/voyage_list.html",voyages=voyages,
                           vessel_name=vessel_name, s_crew=s_crew,
                           line=line, supervisor=supervisor, pagination=pagination)



@vessel_bp.route("/voyage/<int:voyage_id>" , methods=["GET"])
@login_required # 로그인 여부 확인 -> 비 로그인시 로그인 페이지 이동
def voyage_detail(voyage_id):
    # VoyageInfo 테이블에서 해당 ID 조회, 없으면 404
    voyage = VoyageInfo.query.get_or_404(voyage_id)
    return render_template("vessel/voyage_detail.html",voyage=voyage)

templates/vessel/vessel_detail.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vessel_detail.css') }}">
{% endblock %}

{% block content %}
    <div class="vessel-detail-container">
        <div class="inner">
            <div class="title-container"><h1>선박 상세 정보</h1></div>
            <div class="dl-container">
                <dl>
                    <dt>선박이름</dt>
                    <dd>{{ vessel.name }}</dd>

                    <dt>IMO 번호</dt>
                    <dd>{{ vessel.imo_number }}</dd>

                    <dt>선종</dt>
                    <dd>{{ vessel.ship_type }}</dd>

                    <dt>선박사이즈</dt>
                    <dd>{{ vessel.ship_size }}</dd>

                    <dt>기국</dt>
                    <dd>{{ vessel.flag }}</dd>

                    <dt>선박코드</dt>
                    <dd>{{ vessel.detail.ship_code or "-"}}</dd>

                    <dt>RO</dt>
                    <dd>{{ vessel.detail.vessel_ro or "-" }}</dd>

                    <dt>CLASS</dt>
                    <dd>{{ vessel.detail.vessel_class or "-" }}</dd>

                    <dt>건조년도</dt>
                    <dd>{{ vessel.detail.built_year or "-" }}</dd>

                    <dt>관리팀</dt>
                    <dd>{{ vessel.detail.team or "-" }}</dd>

                    <dt>해상인사팀</dt>
                    <dd>{{ vessel.detail.crew or "-" }}</dd>

                </dl>
            </div>
            <div class="btn-position">
                <a href="{{ url_for('vessel.vessel_edit', vessel_id=vessel.id) }}" class="btn-primary">수 정</a>
                <form id="delete-form" action="/vessel/{{ vessel.id }}/delete" method="POST">
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn-danger">삭 제</button>
                </form>
            </div>
        </div>
    </div> 
{% endblock %}

templates/vessel/vessel_edit.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vessel_edit.css') }}">
{% endblock %}


{% block content %}
    <div class="sub-container">
        <div class="inner">
            <div class="title-container"><h1>선박 수정</h1></div>
            <div class="form-container">
                <form action="/vessel/{{ vessel.id }}/edit" method="POST">
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
                    <input type="text" name="name" value="{{ vessel.name }}" required>
                    <input type="number" name="imo_number" value="{{ vessel.imo_number }}" required min="1000000" max="9999999">
                    <select name="ship_type" required>
                        <option value="" disabled>선종 선택</option>
                        <option value="CNTR" {% if vessel.ship_type == "CNTR" %}selected{% endif %}>컨테이너선</option>
                        <option value="TNKR" {% if vessel.ship_type == "TNKR" %}selected{% endif %}>유조선</option>
                        <option value="GAS" {% if vessel.ship_type == "GAS" %}selected{% endif %}>가스운반선</option>
                        <option value="BULK" {% if vessel.ship_type == "BULK" %}selected{% endif %}>벌크선</option>
                        <option value="PCTC" {% if vessel.ship_type == "PCTC" %}selected{% endif %}>PCTC</option>
                        <option value="MPV" {% if vessel.ship_type == "MPV" %}selected{% endif %}>MPV</option>
                    </select>
                    <input type="text" name="ship_size" value="{{ vessel.ship_size }}" required>
                    <select name="flag" required>
                        <option value="" disabled >기국 선택</option>
                        <option value="KOR" {% if vessel.flag == "KOR" %}selected{% endif %}>대한민국</option>
                        <option value="PAN" {% if vessel.flag == "PAN" %}selected{% endif %}>파나마</option>
                        <option value="LIB" {% if vessel.flag == "LIB" %}selected{% endif %}>라이베리아</option>
                        <option value="MAR" {% if vessel.flag == "MAR" %}selected{% endif %}>마샬</option>
                        <option value="SIN" {% if vessel.flag == "SIN" %}selected{% endif %}>싱가폴</option>
                    </select>
                    <input type="text" name="ship_code" value="{{ vessel.detail.ship_code }}" placeholder="선박코드" required>
                    <input type="text" name="vessel_ro" value="{{ vessel.detail.vessel_ro }}"  placeholder="RO" required>
                    <input type="text" name="vessel_class" value="{{ vessel.detail.vessel_class }}" placeholder="선급" required>
                    <input type="text" name="built_year" value="{{ vessel.detail.built_year}}" placeholder="건조년월(2021-04)">
                    <select name="team" required>
                        <option value="" disabled >관리팀 선택</option>
                        <option value="C1T" {% if vessel.detail.team == "C1T" %}selected{% endif %}>컨테이너선1팀</option>
                        <option value="C2T" {% if vessel.detail.team == "C2T" %}selected{% endif %}>컨테이너선2팀</option>
                        <option value="C3T" {% if vessel.detail.team == "C3T" %}selected{% endif %}>컨테이너선3팀</option>
                        <option value="C4T" {% if vessel.detail.team == "C4T" %}selected{% endif %}>컨테이너선4팀</option>
                        <option value="TKT" {% if vessel.detail.team == "TKT" %}selected{% endif %}>유조선팀</option>
                        <option value="LBT" {% if vessel.detail.team == "LBT" %}selected{% endif %}>LNG & BULK선팀</option>
                    </select>
                    <select name="crew" required>
                        <option value="" disabled>해상인사팀 선택</option>
                        <option value="CM1" {% if vessel.detail.crew == "CM1" %}selected{% endif %}>해상인사1팀</option>
                        <option value="CM2" {% if vessel.detail.crew == "CM2" %}selected{% endif %}>해상인사2팀</option>
                    </select>
                    <button type="submit" class="btn-primary">수 정</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/vessel/vessel_list.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vessel_list.css') }}">
{% endblock %}

{% block content %}
    <div class="vessel-list-container">
        <div class="inner">
            <div class="title-container"><h1>선박 목록</h1></div>
            <div class="search-box">
                <form method="GET" action="{{ url_for('vessel.vessel_list') }}">
                    <div class="search-box-inner">
                        <input type="hidden" name="page" value="1"> 
                        <input type="text" name="name" placeholder="선박명" value="{{ name }}">
                        <select name="ship_type">
                            <option value="" {% if ship_type == '' %}selected{% endif %}>선종 선택</option>
                            <option value="CNTR" {% if ship_type == 'CNTR' %}selected{% endif %}>컨테이너선</option>
                            <option value="TNKR" {% if ship_type == 'TNKR' %}selected{% endif %}>유조선</option>
                            <option value="GAS" {% if ship_type == 'GAS' %}selected{% endif %}>가스운반선</option>
                            <option value="BULK" {% if ship_type == 'BULK' %}selected{% endif %}>벌크선</option>
                            <option value="PCTC" {% if ship_type == 'PCTC' %}selected{% endif %}>PCTC</option>
                            <option value="MPV" {% if ship_type == 'MPV' %}selected{% endif %}>MPV</option>
                        </select>
                        <select name="flag">
                            <option value="" {% if flag == '' %}selected{% endif %}>기국 선택</option>
                            <option value="KOR" {% if flag == 'KOR' %}selected{% endif %}>대한민국</option>
                            <option value="PAN" {% if flag == 'PAN' %}selected{% endif %}>파나마</option>
                            <option value="LIB" {% if flag == 'LIB' %}selected{% endif %}>라이베리아</option>
                            <option value="MAR" {% if flag == 'MAR' %}selected{% endif %}>마샬</option>
                            <option value="SIN" {% if flag == 'SIN' %}selected{% endif %}>싱가폴</option>
                        </select>
                    </div>
                    <button type="submit" class="btn-primary">검색</button>
                </form>
            </div>
            <div class="table-container">
                <table>
                    <thead>
                        <tr>
                            <th>선박명</th>
                            <th>IMO 번호</th>
                            <th>선종</th>
                            <th>SIZE</th>
                            <th>기국</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for vessel in vessels %}
                        <tr>
                            <td><a href="{{ url_for('vessel.vessel_detail', vessel_id=vessel.id)}}">{{ vessel.name }}</a></td>
                            <td>{{ vessel.imo_number }}</td>
                            <td>{{ vessel.ship_type }}</td>
                            <td>{{ vessel.ship_size }}</td>
                            <td>{{ vessel.flag }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="pagination">
                {% if pagination.has_prev %}
                    <a href="{{ url_for('vessel.vessel_list', page=pagination.prev_num, name=name, ship_type = ship_type, flag=flag) }}">이전</a>
                {% endif %}

                {% for p in pagination.iter_pages() %}
                    {% if p %}
                        <a href="{{ url_for('vessel.vessel_list', page = p, name=name, ship_type = ship_type, flag=flag) }}" 
                        {% if p == pagination.page %} class="active" {% endif %}>{{ p }}</a>
                    {% else %}
                        <span>...</span>
                    {% endif %}
                {% endfor %}

                {% if pagination.has_next %}
                    <a href="{{ url_for('vessel.vessel_list', page=pagination.next_num, name=name, ship_type=ship_type, flag=flag) }}">다음</a>
                {% endif %}
                </div>  
            </div>
        </div>
    </div> 
{% endblock %}

templates/vessel/vessel_new.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vessel_new.css') }}">
{% endblock %}


{% block content %}
    <div class="sub-container">
        <div class="inner">
            <div class="title-container"><h1>선박 등록</h1></div>
            <div class="form-container">
                <form action="/vessel/new" method="POST">
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
                    <input type="text" name="name" placeholder="선박명" required>
                    <input type="number" name="imo_number" placeholder="IMO 번호" required min="1000000" max="9999999">
                    <select name="ship_type" required>
                        <option value="" disabled selected>선종 선택</option>
                        <option value="CNTR">컨테이너선</option>
                        <option value="TNKR">유조선</option>
                        <option value="GAS">가스운반선</option>
                        <option value="BULK">벌크선</option>
                        <option value="PCTC">PCTC</option>
                        <option value="MPV">MPV</option>
                    </select>
                    <input type="text" name="ship_size" placeholder="선박사이즈(24k,VLCC)" required>
                    <select name="flag" required>
                        <option value="" disabled selected>기국 선택</option>
                        <option value="KOR">대한민국</option>
                        <option value="PAN">파나마</option>
                        <option value="LIB">라이베리아</option>
                        <option value="MAR">마샬</option>
                        <option value="SIN">싱가폴</option>
                    </select>
                    <input type="text" name="ship_code" placeholder="선박코드" required>
                    <input type="text" name="vessel_ro" placeholder="선박 RO" required>
                    <input type="text" name="vessel_class" placeholder="선급" required>
                    <input type="text" name="built_year" placeholder="건조년월(2021-04)">
                    <select name="team" required>
                        <option value="" disabled selected>관리팀 선택</option>
                        <option value="C1T">컨테이너선1팀</option>
                        <option value="C2T">컨테이너선2팀</option>
                        <option value="C3T">컨테이너선3팀</option>
                        <option value="C4T">컨테이너선4팀</option>
                        <option value="TKT">유조선팀</option>
                        <option value="LBT">LNG & BULK선팀</option>
                    </select>
                    <select name="crew" required>
                        <option value="" disabled selected>해상인사팀 선택</option>
                        <option value="CM1">해상인사1팀</option>
                        <option value="CM2">해상인사2팀</option>
                    </select>
                    <button type="submit" class="btn-primary">등 록</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/vessel/voyage_detail.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/voyage_detail.css') }}">
{% endblock %}

{% block content %}
    <div class="vessel-detail-container">
        <div class="inner">
            <div class="title-container"><h1>선박 상세 정보</h1></div>
            <div class="dl-container">
                <dl>
                    <dt>선박이름</dt>
                    <dd>{{ voyage.vessel_name }}</dd>

                    <dt>항차정보</dt>
                    <dd>{{ voyage.voy_no }}</dd>

                    <dt>항로</dt>
                    <dd>{{ voyage.line }}</dd>

                    <dt>선장</dt>
                    <dd>{{ voyage.captain }}</dd>

                    <dt>기관장</dt>
                    <dd>{{ voyage.chief_engineer }}</dd>

                    <dt>감독</dt>
                    <dd>{{ voyage.safety_supervisor }}</dd>

                    <dt>운항감독</dt>
                    <dd>{{ voyage.ops_supervisor }}</dd>

                    <dt> 출항항</dt>
                    <dd>{{ voyage.last_port }}</dd>

                    <dt> 출항일</dt>
                    <dd>{{ voyage.last_etd }}</dd>

                    <dt> 입항항 </dt>
                    <dd>{{ voyage.next_port }}</dd>

                    <dt> 입항일 (ETB)</dt>
                    <dd>{{ voyage.next_etb }}</dd>

                    <dt> 항로 </dt>
                    <dd>{{ voyage.itinerary }}</dd>

                    <dt> 최종 업데이트 시간 </dt>
                    <dd>{{ voyage.updated_at }}</dd>

                </dl>
            </div>
            <div class="btn-position">
                  <a href="{{ url_for('vessel.voyage_list') }}" class="btn-primary">목록으로</a>
            </div>
        </div>
    </div> 
{% endblock %}

templates/vessel/voyage_list.html
{% extends "base.html" %}

{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/voyage_list.css') }}">
{% endblock %}

{% block content %}
    <div class="vessel-list-container">
        <div class="inner">
            <div class="title-container"><h1>운항정보</h1></div>
            <div class="search-box">
                <form method="GET" action="{{ url_for('vessel.voyage_list') }}">
                    <div class="search-box-inner">
                        <input type="hidden" name="page" value="1"> 
                        <input type="text" name="vessel_name" placeholder="선박명" value="{{ vessel_name }}">
                        <input type="text" name="line" placeholder="항로" value="{{ line }}">
                        <input type="text" name="s_crew" placeholder="선기장" value="{{ s_crew }}">
                        <input type="text" name="supervisor" placeholder="감독" value="{{ supervisor }}">                      
                    </div>
                    <button type="submit" class="btn-primary">검색</button>
                </form>
            </div>
            <div class="table-container">
                <table>
                    <thead>
                        <tr>
                            <th>선박명</th>
                            <th>운항라인</th>
                            <th>선장</th>
                            <th>기관장</th>
                            <th>담당감독</th>
                            <th>운항감독</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for voyage in voyages %}
                        <tr>
                            <td><a href="{{ url_for('vessel.voyage_detail', voyage_id=voyage.id)}}">{{ voyage.vessel_name}}</a></td>
                            <td>{{ voyage.line }}</td>
                            <td>{{ voyage.captain }}</td>
                            <td>{{ voyage.chief_engineer }}</td>
                            <td>{{ voyage.safety_supervisor }}</td>
                            <td>{{ voyage.ops_supervisor }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="pagination">
                {% if pagination.has_prev %}
                    <a href="{{ url_for('vessel.voyage_list', page=pagination.prev_num, vessel_name=vessel_name, s_crew=s_crew,
                           line=line, supervisor=supervisor,) }}">이전</a>
                {% endif %}

                {% for p in pagination.iter_pages() %}
                    {% if p %}
                        <a href="{{ url_for('vessel.voyage_list', page = p, vessel_name=vessel_name, s_crew=s_crew,
                           line=line, supervisor=supervisor,) }}" 
                        {% if p == pagination.page %} class="active" {% endif %}>{{ p }}</a>
                    {% else %}
                        <span>...</span>
                    {% endif %}
                {% endfor %}

                {% if pagination.has_next %}
                    <a href="{{ url_for('vessel.voyage_list', page=pagination.next_num, vessel_name=vessel_name, s_crew=s_crew,
                           line=line, supervisor=supervisor,) }}">다음</a>
                {% endif %}
                </div> 
            </div>
        </div>
    </div> 
{% endblock %}